package goling

import "testing"

func Test_CosineSimilarity(t *testing.T) {
	// the bigger the return value is,
	// the more similar the two texts are.

	// very similar texts (0.8616404368553293)
	text1 := "This is a foo bar sentence."
	text2 := "This sentence is similar to a foo bar sentence."

	// very different texts (0.04879500364742665)
	text3 := "AppendFloat appends the string form of the floating-point number f, as generated by FormatFloat, to dst and returns the extended buffer."
	text4 := "There are very simple ways to use matlab in parallel, with GPU, multi-thread support."
	if CosineSimilarity(text1, text2) < CosineSimilarity(text3, text4) {
		t.Errorf("Error: text1, text2 should be more similar than text3, text4")
	}

	// less different texts (0.31980107453341566)
	text5 := "How is the product team at SEOmoz structured?"
	text6 := "Moz: How trustworthy is SEOMoz after what they did to DOZ?"

	// same texts (1)
	text7 := "I am a gopher."
	text8 := "I am a gopher."
	if CosineSimilarity(text5, text6) > CosineSimilarity(text7, text8) {
		t.Errorf("Error: text7, text8 should be more simliar than text3, text4")
	}

	// totally different text
	text9 := "I am a gopher."
	text0 := ""
	if CosineSimilarity(text9, text0) != 0.0001 {
		t.Errorf("Error: text9, text10 should return 0.0001 with smoothing")
	}

	if CosineSimilarity("intention", "execution") != 0.6917144638660746 {
		t.Errorf("Error: intention, execution, CosineSimilarity")
	}

	if CosineSimilarity("i n t e n t i o n", "e x e c u t i o n") != 0.6917144638660746 {
		t.Errorf("Error: intention, execution, CosineSimilarity")
	}

	if CosineSimilarity("AGGCTATCACCTGACCTCCAGGCCGATGCC", "TAGCTATCACGACCGCGGTCGATTTGCCCGAC") != 0.9890107762526607 {
		t.Errorf("DNA, CosineSimilarity")
	}

	if CosineSimilarity("like", "lllikee") != 0.9036961141150639 {
		t.Errorf("like", "lllikee", "CosineSimilarity")
	}

	if CosineSimilarity("love it", "go to the beach") != 0.0001 {
		t.Errorf("love it", "go to the beach", "CosineSimilarity")
	}

	if CosineSimilarity("Spokesman confirms senior government adviser was shot.", "Spokesman said the senior adviser was shot dead.") != 0.6681531047810609 {
		t.Errorf("Spokesman, CosineSimilarity")
	}
}
