package goling

import "testing"

func Test_LevenshteinDistance(t *testing.T) {
	// the bigger the return value is,
	// the more similar the two texts are.

	// insertion
	if LevenshteinDistance("Hello", "Hellok") != 1 {
		t.Errorf("Error: LevenshteinDistance")
	}

	// deletion
	if LevenshteinDistance("Hellok", "Hello") != 1 {
		t.Errorf("Error: LevenshteinDistance")
	}

	// substituition
	if LevenshteinDistance("Hellok", "Helloa") != 1 {
		t.Errorf("Error: LevenshteinDistance")
	}

	// very similar texts
	text1 := "This is a foo bar sentence."
	text2 := "This sentence is similar to a foo bar sentence."
	if LevenshteinDistance(text1, text2) != 20 {
		t.Errorf("Error: text1, text2, LevenshteinDistance")
	}

	// very different texts
	text3 := "AppendFloat appends the string form of the floating-point number f, as generated by FormatFloat, to dst and returns the extended buffer."
	text4 := "There are very simple ways to use matlab in parallel, with GPU, multi-thread support."
	if LevenshteinDistance(text3, text4) != 98 {
		t.Errorf("Error: text3, text4, LevenshteinDistance")
	}

	// less different texts
	text5 := "How is the product team at SEOmoz structured?"
	text6 := "Moz: How trustworthy is SEOMoz after what they did to DOZ?"
	if LevenshteinDistance(text5, text6) != 40 {
		t.Errorf("Error: text5, text6, LevenshteinDistance")
	}

	// same texts
	text7 := "I am a gopher."
	text8 := "I am a gopher."
	if LevenshteinDistance(text7, text8) != 0.0001 {
		t.Errorf("Error: text7, text8, LevenshteinDistance")
	}

	// totally different text
	text9 := "I am a gopher."
	text0 := ""
	if LevenshteinDistance(text9, text0) != 14 {
		t.Errorf("Error: text9, text10, LevenshteinDistance")
	}

	if LevenshteinDistance("intention", "execution") != 5 {
		t.Errorf("Error: intention, execution, LevenshteinDistance")
	}

	if LevenshteinDistance("i n t e n t i o n", "e x e c u t i o n") != 5 {
		t.Errorf("Error: intention, execution, LevenshteinDistance")
	}

	if LevenshteinDistance("AGGCTATCACCTGACCTCCAGGCCGATGCC", "TAGCTATCACGACCGCGGTCGATTTGCCCGAC") != 14 {
		t.Errorf("DNA, LevenshteinDistance")
	}

	if LevenshteinDistance("like", "lllikee") != 3 {
		t.Errorf("like", "lllikee", "LevenshteinDistance")
	}

	if LevenshteinDistance("look at", "google") != 5 {
		t.Errorf("like", "lllikee", "LevenshteinDistance")
	}

	if LevenshteinDistance("love it", "go to the beach") != 12 {
		t.Errorf("love it", "go to the beach", "LevenshteinDistance")
	}

	if LevenshteinDistance("Spokesman confirms senior government adviser was shot.", "Spokesman said the senior adviser was shot dead.") != 24 {
		t.Errorf("Spokesman, LevenshteinDistance")
	}
}
