package similar

import "testing"

func TestGet(t *testing.T) {
	text1 := []byte("This is a foo bar sentence.")
	text2 := []byte("This sentence is similar to a foo bar sentence.")
	text3 := []byte("AppendFloat appends the string form of the floating-point number f, as generated by FormatFloat, to dst and returns the extended buffer.")
	text4 := []byte("There are very simple ways to use matlab in parallel, with GPU, multi-thread support.")
	if Get(text1, text2, Cosine, Hamming, Levenshtein) < Get(text3, text4, Cosine, Hamming, Levenshtein) {
		t.Errorf("%v\n%v\n", Get(text1, text2), Get(text3, text4))
	}

	text5 := []byte("How is the product team at SEOmoz structured?")
	text6 := []byte("Moz: How trustworthy is SEOMoz after what they did to DOZ?")
	text7 := []byte("I am a gopher.")
	text8 := []byte("I am a gopher.")
	if Get(text5, text6, Cosine, Hamming, Levenshtein) > Get(text7, text8, Cosine, Hamming, Levenshtein) {
		t.Errorf("%v\n%v\n", Get(text5, text6, Cosine, Hamming, Levenshtein), Get(text7, text8, Cosine, Hamming, Levenshtein))
	}
}
